#! /bin/bash
#stdlib::info starting metadata script

sudo apt-get update
sudo apt-get install -y build-essential python-pip rsync wget
pip install flask
wget https://raw.githubusercontent.com/bobbae/gcp/main/tf/flask/app.py

#stdlib::info end of metadata script
