gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable cloudbilling.googleapis.com
gcloud services enable iam.googleapis.com
gcloud services enable compute.googleapis.com
gcloud services enable serviceusage.googleapis.com
gcloud services enable bigquery.googleapis.com
gcloud services enable servicedirectory.googleapis.com
gcloud services enable cloudasset.googleapis.com
gcloud services enable dns.googleapis.com
gcloud services enable cloudkms.googleapis.com
gcloud services enable logging.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable pubsub.googleapis.com
gcloud services enable storage-component.googleapis.com
gcloud services enable sqladmin.googleapis.com
gcloud services enable containerregistry.googleapis.com
gcloud services enable container.googleapis.com
gcloud services enable serviceusage.googleapis.com
gcloud services enable commentanalyzer.googleapis.com
gcloud services enable cloudapis.googleapis.com
gcloud services enable cloudbuild.googleapis.com
gcloud services enable sourcerepo.googleapis.com
gcloud services enable cloudfunctions.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable bigquery-json.googleapis.com
gcloud services enable clouddebugger.googleapis.com
gcloud services enable datastore.googleapis.com
gcloud services enable storage-api.googleapis.com
gcloud services enable resourceviews.googleapis.com
gcloud services enable replicapool.googleapis.com
gcloud services enable deploymentmanager.googleapis.com
gcloud services enable sql-component.googleapis.com
gcloud services enable monitoring.googleapis.com
gcloud services enable cloudtrace.googleapis.com
gcloud services enable replicapoolupdater.googleapis.com

