apiVersion: v1
kind: Service
metadata:
  name: twilio-vision-webapp
  labels:
    app: twilio-vision
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: "http-server"
  selector:
    app: twilio-vision
    role: frontend
